root = "."
tmp_dir = "tmp"

[build]
cmd = "go run github.com/a-h/templ/cmd/templ@v0.3.1020 generate && go build -o ./tmp/kritui ."
bin = "./tmp/kritui"
full_bin = "env $(xargs < .env) ./tmp/kritui"
include_ext = ["go", "templ", "css"]
exclude_dir = ["tmp"]
exclude_regex = [".*_templ\\.go$"]
stop_on_error = true

[proxy]
enabled = true
proxy_port = 7331
app_port = 8080

[misc]
clean_on_exit = true
